services:
  postgres:
    image: postgres:16
    container_name: erp-postgres

    environment:
      POSTGRES_DB: ventas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../Ventas-Backend

    container_name: erp-backend

    ports:
      - "8081:8081"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ventas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 8081

  frontend:
    build:
      context: ../Ventas-Frontend

    container_name: erp-frontend

    ports:
      - "4200:80"

    depends_on:
      - backend

volumes:
  postgres_data: